### ISSUE TITLE
Recognize identifiers with a number in them

### ISSUE THREAD

**Issue by danerwilliams** [ginglis13/bminor-vim-syntax-highlighting#5]
Identifiers that contain a number in them aren't properly highlighted.

![Screen Shot 2020-10-04 at 4 28 15 PM](https://user-images.githubusercontent.com/22798229/95026326-9d426a00-065e-11eb-8b92-fc7a6dacf16e.jpg)

**Comment by danerwilliams** [comment]
Going to look in to a fix for this when I get a chance later.

**Comment by ginglis13** [comment]
Closing b/c #6. Thanks for the contributions, guys!
